### ISSUE TITLE
Sometimes occurs an exception

### ISSUE THREAD

**Issue by ken-kentan** [xaniox/HeavySpleef#21]
[HeavySpleef] Task #75 for HeavySpleef v2.3 generated an exception java.lang.IllegalArgumentException: Cannot drop AIR.
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.8.8.jar:git-Spigotdb6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItem(CraftWorld.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at de.xaniox.heavyspleef.core.player.PlayerStateHolder.apply(PlayerStateHolder.java:140) ~[?:?]
        at de.xaniox.heavyspleef.core.game.Game.leave(Game.java:721) ~[?:?]
        at de.xaniox.heavyspleef.core.game.Game.requestWin(Game.java:866) ~[?:?]
        at de.xaniox.heavyspleef.core.game.Game.requestWin(Game.java:859) ~[?:?]
        at de.xaniox.heavyspleef.core.game.Game.requestLose(Game.java:848) ~[?:?]
        at de.xaniox.heavyspleef.core.game.Game.requestLose(Game.java:835) ~[?:?]
        at de.xaniox.heavyspleef.core.game.LoseCheckerTask.run(LoseCheckerTask.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by xaniox** [comment]
This issue has been fixed in the latest development build. 

You can download it on my ci server: [https://ci.xaniox.de/job/HeavySpleef/](url)
