### ISSUE TITLE
Issue with joining to game by command while warmup mode

### ISSUE THREAD

**Issue by Ghostlyr** [xaniox/HeavySpleef#47]
Sometimes players fall under arena when joining to game with join command while game starting with warmup mode.

Last dev version HS.
Last build of spigot for old 1.7.10 version (⌒_⌒;)
Installed addons: AnvilSpleef, Leaderboard.
No other plugins, which could affect player teleportation.

**Comment by Ghostlyr** [comment]
Few new issues with warmup mode

1. Warmup teleportation occurs even if players leave the game.
2. Warmup teleportation occurs even game was over by leaving players.

And in the latter case plugin throws the exception: 
```
[HeavySpleef] Could not pass PlayerWinGameEvent in class de.xaniox.heavyspleef.core.stats.StatisticRecorder
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.xaniox.heavyspleef.core.event.EventListenerMethod.invoke(EventListenerMethod.java:70) ~[HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.event.EventBus.callEvent(EventBus.java:96) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.game.Game.requestWin(Game.java:944) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.game.Game.requestWin(Game.java:922) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.game.Game.requestLose(Game.java:911) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.game.Game.requestLose(Game.java:898) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.extension.LeaveSignExtension.onSignClick(LeaveSignExtension.java:61) [HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.extension.SignExtension.onPlayerInteract(SignExtension.java:192) [HeavySpleef%20(3).jar:?]
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:382) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at de.xaniox.heavyspleef.core.event.EventListenerMethod.invoke(EventListenerMethod.java:68) ~[HeavySpleef%20(3).jar:?]
	... 26 more
Caused by: java.lang.IllegalArgumentException: Dead players list does not contain a player with the name Ghostly
	at de.xaniox.heavyspleef.core.game.DefaultRatingCompute.getPlace(DefaultRatingCompute.java:68) ~[HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.game.DefaultRatingCompute.compute(DefaultRatingCompute.java:50) ~[HeavySpleef%20(3).jar:?]
	at de.xaniox.heavyspleef.core.stats.StatisticRecorder.onPlayerWinGame(StatisticRecorder.java:139) ~[HeavySpleef%20(3).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at de.xaniox.heavyspleef.core.event.EventListenerMethod.invoke(EventListenerMethod.java:68) ~[HeavySpleef%20(3).jar:?]
	... 26 more
```

**Comment by xaniox** [comment]
I fixed the three bugs you detected in the latest development build but I still have no idea why players fall under the arena...

**Comment by Ghostlyr** [comment]
Thank you.
Looks like problem with falling under arena associated physics of the game, because was observed only in the arena with TNT floors. Spawn point has been set directly on the block, I tried to install two blocks above and issue was not noticed again.
