### ISSUE TITLE
Leaderboard/top not loading

### ISSUE THREAD

**Issue by sNuuFix** [xaniox/HeavySpleef#54]
We are on 1.11.2 PaperSpigot and with game stats saved in MySQL. The data is there, but when executing `/spleef stats top` or using Leaderboard Add-On the console gets this error:

`[Server thread/WARN]: [HeavySpleef] Cannot retrieve top statistics for leaderboard wall
java.util.concurrent.ExecutionException: Unexpected token END OF FILE at position 0.
        at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137) ~                                             [?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[?:?]
        at de.xaniox.heavyspleef.core.uuid.UUIDManager.getProfile(UUIDManager.java:254) ~[?:?]
        at de.xaniox.heavyspleef.persistence.handler.CachingReadWriteHandler.getTopStatistics(CachingReadWriteHandler.java:512) ~[?:?]
        at de.xaniox.heavyspleef.persistence.handler.ForwardingAsyncReadWriteHandler$16.call(ForwardingAsyncReadWriteHandler.java:222)                                              ~[?:?]
        at de.xaniox.heavyspleef.persistence.handler.ForwardingAsyncReadWriteHandler$16.call(ForwardingAsyncReadWriteHandler.java:218)                                              ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.json.simple.parser.ParseException
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[paperclip.jar:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[paperclip.jar:?]
        at de.xaniox.heavyspleef.core.uuid.UUIDManager.fetchGameProfile(UUIDManager.java:368) ~[?:?]
        at de.xaniox.heavyspleef.core.uuid.UUIDManager.access$200(UUIDManager.java:41) ~[?:?]
        at de.xaniox.heavyspleef.core.uuid.UUIDManager$2.load(UUIDManager.java:99) ~[?:?]
        at de.xaniox.heavyspleef.core.uuid.UUIDManager$2.load(UUIDManager.java:95) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[?:?]
        at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[?:?]
        ... 13 more
`

**Comment by Ghostlyr** [comment]
Have a same issue when running server with offline-mode (BungeeCord).
  
```
[HeavySpleef] Could not load top statistic list: 
java.util.concurrent.ExecutionException: Unexpected token END OF FILE at position 0.
	at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[?:?]
	at de.xaniox.heavyspleef.core.uuid.UUIDManager.getProfile(UUIDManager.java:254) ~[?:?]
	at de.xaniox.heavyspleef.persistence.handler.CachingReadWriteHandler.getTopStatistics(CachingReadWriteHandler.java:519) ~[?:?]
	at de.xaniox.heavyspleef.persistence.handler.ForwardingAsyncReadWriteHandler$16.call(ForwardingAsyncReadWriteHandler.java:222) ~[?:?]
	at de.xaniox.heavyspleef.persistence.handler.ForwardingAsyncReadWriteHandler$16.call(ForwardingAsyncReadWriteHandler.java:218) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: org.json.simple.parser.ParseException
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[spigot.jar:git-Spigot-3d850ec-f46ccd7]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[spigot.jar:git-Spigot-3d850ec-f46ccd7]
	at de.xaniox.heavyspleef.core.uuid.UUIDManager.fetchGameProfile(UUIDManager.java:368) ~[?:?]
	at de.xaniox.heavyspleef.core.uuid.UUIDManager.access$200(UUIDManager.java:41) ~[?:?]
	at de.xaniox.heavyspleef.core.uuid.UUIDManager$2.load(UUIDManager.java:99) ~[?:?]
	at de.xaniox.heavyspleef.core.uuid.UUIDManager$2.load(UUIDManager.java:95) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[?:?]
	at de.xaniox.heavyspleef.lib.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[?:?]
	... 13 more
```

Need simply try-catch `IOException` & `ParseException`
