### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by dhunter49** [xaniox/HeavySpleef#78]
[21:45:49] [Server thread/ERROR]: [HeavySpleef] Exception occured while saving data: 
java.lang.NullPointerException
at de.xaniox.heavyspleef.core.extension.SignExtension.marshal(SignExtension.java:198) ~[?:?]
at de.xaniox.heavyspleef.persistence.xml.GameAccessor.write(GameAccessor.java:138) ~[?:?]
at de.xaniox.heavyspleef.persistence.xml.GameAccessor.write(GameAccessor.java:55) ~[?:?]
at de.xaniox.heavyspleef.persistence.xml.XMLContext.write(XMLContext.java:41) ~[?:?]
at de.xaniox.heavyspleef.persistence.handler.CachingReadWriteHandler.saveGame(CachingReadWriteHandler.java:189) ~[?:?]
at de.xaniox.heavyspleef.persistence.handler.CachingReadWriteHandler.saveGames(CachingReadWriteHandler.java:175) ~[?:?]
at de.xaniox.heavyspleef.commands.CommandSave$SaveOperation$3$1.executeBatch(CommandSave.java:92) ~[?:?]
at de.xaniox.heavyspleef.core.persistence.OperationBatch.call(OperationBatch.java:32) ~[?:?]
at de.xaniox.heavyspleef.core.persistence.OperationBatch.call(OperationBatch.java:25) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by dhunter49** [comment]
No answer?

**Comment by dhunter49** [comment]
I won't wait for years to answer. Plugin is dead
